### ISSUE TITLE
DOA Accuracy Issue.

### ISSUE THREAD

**Issue by sradmard** [furushchev/respeaker_ros#13]
Hi,
This is not an issue with this ros package, and it is primarily about the Respeaker Mic array V2. 
I was wondering whether anyone else is experiencing quite a significant inaccuracy in the DOA detection by Respeaker V2. I have used both this ros package and their own provided python code to get the DOA, but it is usually quite off in the order of about 90 to 180 degrees. 
I would appreciate any hint on how to improve it in case anyone has experienced it. 
Thank you so much in advance.

**Comment by furushchev** [comment]
Hi,
Unfortunately, this package only uses the value from the sensor and do not any post processing. 
I sometimes see such bad recognitions when the sound is quite loud and reflects surrounding walls, which I think it is beyond the limit of this device. 
Anyway, there is an official forum that I recommend you to post your issue.
https://forum.seeedstudio.com/viewforum.php?f=87&sid=8458b509b58f067baa01c756ca4c9e35
Hope it will help you. 

I will close the issue now since there is nothing to do with this package.
