### ISSUE TITLE
action 'sound_play' is not initialized.

### ISSUE THREAD

**Issue by feifeiwei** [furushchev/respeaker_ros#16]
hey, when i run roslaunch respeaker_ros respeaker.launch,  i got a mistake,  
[ERROR] action  'sound_play' is not initialized.
any suggestions?
your sincerely

**Comment by furushchev** [comment]
@feifeiwei Hi, I guess that you got the error because you run `speech_to_text.py` with `self_cancellation` option enabled (which is enabled by default) but `sound_play` node (which is necessary to work with self_cancellation mode) is not running.

This function is for disabling microphone during any sound is being played from a speaker in order to avoid mis-recognition.
If you don't use this feature, you can just ignore the error message.

**Comment by feifeiwei** [comment]
i have got it,  thank you~
